import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Button } from '@/components/atoms/Button'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Write Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full flex flex-col items-center pt-40'>
        <h1 className='font-bold text-5xl text-slate-300'>Write.Me</h1>
        <p className='text-slate-300 mb-8'>Markdown editor</p>
        <Button>
          <Link href={'/editor'}>
            Start editing
          </Link>
        </Button>
      </main>
    </>
  )
}
